import tkinter as tk
import os.path

#mysql.connector is used for connecting and interacting with the database
#messagebox is for pop ups
import mysql.connector
import messagebox

_location = os.path.dirname(__file__)

# import MainPage_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black'
_tabfg2 = 'white'
_bgmode = 'light'
_tabbg1 = '#d9d9d9'
_tabbg2 = 'gray40'

#all the process happens in this class, starts with constructor making the backpage(dark blue) then on that same page we
#remove and put buttons and texts by calling functions
class Toplevel1:
    #below fn. are used for CRUD operations, when a button is pressed these are called
    def ADD(self):
        mycursor = self.mydb.cursor()
        #get() fn. requires the starting and ending from the text box(we always read all of the text so 1 to end)
        mycursor.execute(
            f"INSERT INTO students VALUES({self.Text1.get('1.0', 'end')},'{self.Text2.get('1.0', 'end')}','{self.Text3.get('1.0', 'end')}',{self.Text4.get('1.0', 'end')},'{self.Text5.get('1.0', 'end')}', '{self.Text7.get('1.0', 'end')}')")
        # commit() is used to actually make the changes to database(execute)
        self.mydb.commit()
        # a pop up
        messagebox.showinfo("ADD Student", f"Adding Student of ID: {self.Text1.get('1.0', 'end')}")
        #to show updated list
        self.showdetails()

    def ADDt(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(
            f"INSERT INTO Teachers VALUES({self.Text1.get('1.0', 'end')},'{self.Text2.get('1.0', 'end')}','{self.Text3.get('1.0', 'end')}','{self.Text4.get('1.0', 'end')}','{self.Text5.get('1.0', 'end')}', '{self.Text7.get('1.0', 'end')}')")
        self.mydb.commit()
        messagebox.showinfo("ADD Teacher", f"Adding Teacher of ID: {self.Text1.get('1.0', 'end')}")
        self.showdetailst()

    def ADDat(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(
            f"INSERT INTO Accounts (account_id,username,password,salary,teacher_id) VALUES ({self.Text1.get('1.0', 'end')},'{self.Text2.get('1.0', 'end')}','{self.Text3.get('1.0', 'end')}',{self.Text4.get('1.0', 'end')},{self.Text5.get('1.0', 'end')})")
        self.mydb.commit()
        messagebox.showinfo("ADD Account", f"Adding Account of ID: {self.Text1.get('1.0', 'end')}")
        self.showdetailsa()

    def ADDas(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(
            f"INSERT INTO Accounts (account_id,username,password,salary,staff_id) VALUES ({self.Text1.get('1.0', 'end')},'{self.Text2.get('1.0', 'end')}','{self.Text3.get('1.0', 'end')}',{self.Text4.get('1.0', 'end')},{self.Text7.get('1.0', 'end')})")
        self.mydb.commit()
        messagebox.showinfo("ADD Account", f"Adding Account of ID: {self.Text1.get('1.0', 'end')}")
        self.showdetailsa()

    def ADDl(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(
            f"INSERT INTO Library VALUES({self.Text1.get('1.0', 'end')},'{self.Text2.get('1.0', 'end')}','{self.Text3.get('1.0', 'end')}',{self.Text4.get('1.0', 'end')},'{self.Text5.get('1.0', 'end')}')")
        self.mydb.commit()
        messagebox.showinfo("ADD Library", f"Adding Library of ID: {self.Text1.get('1.0', 'end')}")
        self.showdetailsl()

    def ADDs(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(
            f"INSERT INTO Staff VALUES({self.Text1.get('1.0', 'end')},'{self.Text2.get('1.0', 'end')}','{self.Text3.get('1.0', 'end')}','{self.Text4.get('1.0', 'end')}','{self.Text5.get('1.0', 'end')}')")
        self.mydb.commit()
        messagebox.showinfo("ADD Staff", f"Adding Staff of ID: {self.Text1.get('1.0', 'end')}")
        self.showdetailss()

    def Update(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(
            f"UPDATE students SET stud_id = {self.Text1.get('1.0', 'end')}, Name = '{self.Text2.get('1.0', 'end')}',class = '{self.Text3.get('1.0', 'end')}',Grade = {self.Text4.get('1.0', 'end')},Gender = '{self.Text5.get('1.0', 'end')}', dob = '{self.Text7.get('1.0', 'end')}' WHERE stud_id = {self.Text6.get('1.0', 'end')} ")
        self.mydb.commit()
        messagebox.showinfo("Update Student", f"Update Student whose stud_id is {self.Text6.get('1.0', 'end')}")
        self.showdetails()

    def Updatet(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(
            f"UPDATE Teachers SET teac_id = {self.Text1.get('1.0', 'end')}, Name = '{self.Text2.get('1.0', 'end')}',class = '{self.Text3.get('1.0', 'end')}',Subject = '{self.Text4.get('1.0', 'end')}',Gender = '{self.Text5.get('1.0', 'end')}', dob = '{self.Text7.get('1.0', 'end')}' WHERE teac_id = {self.Text6.get('1.0', 'end')} ")
        self.mydb.commit()
        messagebox.showinfo("Update Teacher", f"Update Teacher whose ID is {self.Text6.get('1.0', 'end')}")
        self.showdetailst()

    def Updateat(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(
            f"UPDATE Accounts SET account_id = {self.Text1.get('1.0', 'end')}, username = '{self.Text2.get('1.0', 'end')}',password = '{self.Text3.get('1.0', 'end')}',salary = {self.Text4.get('1.0', 'end')}, teacher_id = {self.Text5.get('1.0', 'end')} WHERE account_id = {self.Text6.get('1.0', 'end')} ")
        self.mydb.commit()
        messagebox.showinfo("Update Account", f"Update Account whose account_id is {self.Text6.get('1.0', 'end')}")
        self.showdetailsa()

    def Updateas(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(
            f"UPDATE Accounts SET account_id = {self.Text1.get('1.0', 'end')}, username = '{self.Text2.get('1.0', 'end')}',password = '{self.Text3.get('1.0', 'end')}',salary = {self.Text4.get('1.0', 'end')}, staff_id = {self.Text7.get('1.0', 'end')} WHERE account_id = {self.Text6.get('1.0', 'end')} ")
        self.mydb.commit()
        messagebox.showinfo("Update Account", f"Update Account whose account_id is {self.Text6.get('1.0', 'end')}")
        self.showdetailsa()

    def Updatel(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(
            f"UPDATE Library SET book_id = {self.Text1.get('1.0', 'end')}, title = '{self.Text2.get('1.0', 'end')}',author = '{self.Text3.get('1.0', 'end')}',book_price = {self.Text4.get('1.0', 'end')},genre = '{self.Text5.get('1.0', 'end')}' WHERE book_id = {self.Text6.get('1.0', 'end')} ")
        self.mydb.commit()
        messagebox.showinfo("Update Library", f"Update Library whose book_id is {self.Text6.get('1.0', 'end')}")
        self.showdetailsl()

    def Updates(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(
            f"UPDATE staff SET staff_id = {self.Text1.get('1.0', 'end')}, Name = '{self.Text2.get('1.0', 'end')}', position = '{self.Text3.get('1.0', 'end')}',Gender = '{self.Text4.get('1.0', 'end')}', dob = '{self.Text5.get('1.0', 'end')}' WHERE staff_id = {self.Text6.get('1.0', 'end')} ")
        self.mydb.commit()
        messagebox.showinfo("Update Staff", f"Update Staff whose staff_id is {self.Text6.get('1.0', 'end')}")
        self.showdetailss()

    def Delete(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(f"DELETE FROM students WHERE stud_id= {self.Text6.get('1.0', 'end')}")
        self.mydb.commit()
        messagebox.showinfo("Delete Student", f"Deleting students of stud_id: {self.Text6.get('1.0', 'end')}")
        self.showdetails()

    def Deletet(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(f"DELETE FROM Teachers WHERE teac_id={self.Text6.get('1.0', 'end')}")
        self.mydb.commit()
        messagebox.showinfo("Delete Teacher", f"Deleting Teacher of ID: {self.Text6.get('1.0', 'end')} ")
        self.showdetailst()

    def Deletea(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(f"DELETE FROM Accounts WHERE account_id={self.Text6.get('1.0', 'end')}")
        self.mydb.commit()
        messagebox.showinfo("Delete Account", f"Deleting Account of account_id: {self.Text6.get('1.0', 'end')} ")
        self.showdetailsa()

    def Deletel(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(f"DELETE FROM Library WHERE book_id={self.Text6.get('1.0', 'end')}")
        self.mydb.commit()
        messagebox.showinfo("Delete Library", f"Deleting Library of book_id: {self.Text6.get('1.0', 'end')} ")
        self.showdetailsl()

    def Deletes(self):
        mycursor = self.mydb.cursor()
        mycursor.execute(f"DELETE FROM Staff WHERE staff_id= {self.Text6.get('1.0', 'end')}")
        self.mydb.commit()
        messagebox.showinfo("Delete Staff", f"Deleting students of staff_id: {self.Text6.get('1.0', 'end')}")
        self.showdetailss()

    def showdetails(self):
        mycursor = self.mydb.cursor()
        mycursor.execute("SELECT * FROM students")
        myresult = mycursor.fetchall()
        # to clean the list before showing
        self.list1.delete(0, self.list1.size())
        # loop to show it line by line
        for i in range(0, len(myresult)):
            self.list1.insert(i, myresult[i])

    def showdetailst(self):
        mycursor = self.mydb.cursor()

        mycursor.execute("SELECT * FROM Teachers")
        myresult = mycursor.fetchall()
        # to clean the list before showing
        self.list1.delete(0, self.list1.size())

        for i in range(0, len(myresult)):
            self.list1.insert(i, myresult[i])

    def showdetailsa(self):
        mycursor = self.mydb.cursor()

        mycursor.execute("SELECT * FROM Accounts")
        myresult = mycursor.fetchall()
        # to clean the list before showing
        self.list1.delete(0, self.list1.size())

        for i in range(0, len(myresult)):
            self.list1.insert(i, myresult[i])

    def showdetailsl(self):
        mycursor = self.mydb.cursor()

        mycursor.execute("SELECT * FROM Library")
        myresult = mycursor.fetchall()
        # to clean the list before showing
        self.list1.delete(0, self.list1.size())

        for i in range(0, len(myresult)):
            self.list1.insert(i, myresult[i])

    def showdetailss(self):
        mycursor = self.mydb.cursor()

        mycursor.execute("SELECT * FROM Staff")
        myresult = mycursor.fetchall()
        # to clean the list before showing
        self.list1.delete(0, self.list1.size())

        for i in range(0, len(myresult)):
            self.list1.insert(i, myresult[i])

    # F end

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        # below we are making the connection to sql

        self.mydb = mysql.connector.connect(
            host="localhost",
            user="root",
            password="fsa3121",
            database="School"
        )
        # now we set our top level (main backpage)
        top.geometry("600x470+468+138")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1, 1)
        top.title("Toplevel 0")
        top.configure(background="#000080")
        top.configure(highlightbackground="cornsilk4")
        top.configure(highlightcolor="#302855")

        self.top = top

        self.menubar = tk.Menu(top, font="TkMenuFont", bg='cornsilk4', fg=_fgcolor)
        top.configure(menu=self.menubar)
        # below function is called to start from homepage
        self.Homepage()

    def Homepage(self):
        #first we remove whatever buttons are on the page (eg. coming back from student page, we have all buttons and texts and frames of that page,we remove it)
        for i in self.top.winfo_children():
            i.destroy()

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.0, rely=0.045, height=74, width=604)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#000080")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#68665a")
        self.Label1.configure(font="-family {Arial} -size 28 -weight bold")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="cornsilk4")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''BAHRIA FOUNDATION COLLEGE''')

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.033, rely=0.223, relheight=0.696
                          , relwidth=0.925)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#7171ff")
        self.Frame1.configure(highlightbackground="cornsilk4")
        self.Frame1.configure(highlightcolor="black")

        self.bnstu = tk.Button(self.Frame1)
        self.bnstu.place(relx=0.396, rely=0.058, height=46, width=117)
        self.bnstu.configure(activebackground="#d9d9d9")
        self.bnstu.configure(activeforeground="black")
        self.bnstu.configure(background="#bfbfff")
        self.bnstu.configure(disabledforeground="#68665a")
        self.bnstu.configure(font="-family {Arial Black} -size 16 -weight bold")
        self.bnstu.configure(foreground="black")
        self.bnstu.configure(highlightbackground="cornsilk4")
        self.bnstu.configure(highlightcolor="black")
        self.bnstu.configure(text='''Students''', command=self.StudentPage) # here we put the command to call the fn. StudentPage when this button is preesed

        self.bnstuff = tk.Button(self.Frame1)
        self.bnstuff.place(relx=0.396, rely=0.612, height=46, width=117)
        self.bnstuff.configure(activebackground="#d9d9d9")
        self.bnstuff.configure(activeforeground="black")
        self.bnstuff.configure(background="#bfbfff")
        self.bnstuff.configure(disabledforeground="#68665a")
        self.bnstuff.configure(font="-family {Arial Black} -size 15 -weight bold")
        self.bnstuff.configure(foreground="black")
        self.bnstuff.configure(highlightbackground="cornsilk4")
        self.bnstuff.configure(highlightcolor="black")
        self.bnstuff.configure(text='''Staff''', command=self.StaffPage)

        self.bnacc = tk.Button(self.Frame1)
        self.bnacc.place(relx=0.396, rely=0.428, height=46, width=117)
        self.bnacc.configure(activebackground="#d9d9d9")
        self.bnacc.configure(activeforeground="black")
        self.bnacc.configure(background="#bfbfff")
        self.bnacc.configure(disabledforeground="#68665a")
        self.bnacc.configure(font="-family {Arial Black} -size 15 -weight bold")
        self.bnacc.configure(foreground="black")
        self.bnacc.configure(highlightbackground="cornsilk4")
        self.bnacc.configure(highlightcolor="black")
        self.bnacc.configure(text='''Accounts''', command=self.AccountPage)

        self.bntea = tk.Button(self.Frame1)
        self.bntea.place(relx=0.396, rely=0.245, height=46, width=117)
        self.bntea.configure(activebackground="#d9d9d9")
        self.bntea.configure(activeforeground="black")
        self.bntea.configure(background="#bfbfff")
        self.bntea.configure(disabledforeground="#68665a")
        self.bntea.configure(font="-family {Arial Black} -size 15 -weight bold")
        self.bntea.configure(foreground="black")
        self.bntea.configure(highlightbackground="cornsilk4")
        self.bntea.configure(highlightcolor="black")
        self.bntea.configure(text='''Teachers''', command=self.TeacherPage)

        self.bnlib = tk.Button(self.Frame1)
        self.bnlib.place(relx=0.396, rely=0.795, height=46, width=117)
        self.bnlib.configure(activebackground="#d9d9d9")
        self.bnlib.configure(activeforeground="black")
        self.bnlib.configure(background="#bfbfff")
        self.bnlib.configure(disabledforeground="#68665a")
        self.bnlib.configure(font="-family {Arial Black} -size 15 -weight bold")
        self.bnlib.configure(foreground="black")
        self.bnlib.configure(highlightbackground="cornsilk4")
        self.bnlib.configure(highlightcolor="black")
        self.bnlib.configure(text='''Library''', command=self.LibraryPage)

    def StudentPage(self):

        for i in self.top.winfo_children():
            i.destroy()

        self.Label6 = tk.Label(self.top)
        self.Label6.place(relx=0.35, rely=0.0, height=41, width=184)
        self.Label6.configure(activebackground="#d9d9d9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#8588fc")
        self.Label6.configure(compound='left')
        self.Label6.configure(disabledforeground="#68665a")
        self.Label6.configure(font="-family {Arial Black} -size 22 -weight bold")
        self.Label6.configure(foreground="black")
        self.Label6.configure(highlightbackground="cornsilk4")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''STUDENTS''')

        self.list1 = tk.Listbox(self.top)
        self.list1.place(relx=0.067, rely=0.549, relheight=0.363, relwidth=0.86)
        self.list1.configure(background="#ffffff")
        self.list1.configure(disabledforeground="#68665a")
        self.list1.configure(font="TkFixedFont")
        self.list1.configure(foreground="black")
        self.list1.configure(highlightbackground="cornsilk4")
        self.list1.configure(highlightcolor="black")
        self.list1.configure(selectbackground="#d9d9d9")
        self.list1.configure(selectforeground="black")

        self.bnback = tk.Button(self.top)
        self.bnback.place(relx=0.067, rely=0.922, height=36, width=77)
        self.bnback.configure(activebackground="#d9d9d9")
        self.bnback.configure(activeforeground="black")
        self.bnback.configure(background="#bfbfff")
        self.bnback.configure(disabledforeground="#68665a")
        self.bnback.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnback.configure(foreground="black")
        self.bnback.configure(highlightbackground="cornsilk4")
        self.bnback.configure(highlightcolor="black")
        self.bnback.configure(text='''Back''', command=self.Homepage)

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.067, rely=0.098, relheight=0.433
                          , relwidth=0.858)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#7171ff")
        self.Frame1.configure(highlightbackground="cornsilk4")
        self.Frame1.configure(highlightcolor="black")

        self.bnDelete = tk.Button(self.Frame1)
        self.bnDelete.place(relx=0.738, rely=0.633, height=26, width=97)
        self.bnDelete.configure(activebackground="#d9d9d9")
        self.bnDelete.configure(activeforeground="black")
        self.bnDelete.configure(background="#bfbfff")
        self.bnDelete.configure(disabledforeground="#68665a")
        self.bnDelete.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnDelete.configure(foreground="black")
        self.bnDelete.configure(highlightbackground="cornsilk4")
        self.bnDelete.configure(highlightcolor="black")
        self.bnDelete.configure(text='''DELETE''', command=self.Delete)

        self.bnShow = tk.Button(self.Frame1)
        self.bnShow.place(relx=0.738, rely=0.814, height=26, width=97)
        self.bnShow.configure(activebackground="#d9d9d9")
        self.bnShow.configure(activeforeground="black")
        self.bnShow.configure(background="#bfbfff")
        self.bnShow.configure(disabledforeground="#68665a")
        self.bnShow.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnShow.configure(foreground="black")
        self.bnShow.configure(highlightbackground="cornsilk4")
        self.bnShow.configure(highlightcolor="black")
        self.bnShow.configure(text='''SHOW''', command=self.showdetails)

        self.bnAdd = tk.Button(self.Frame1)
        self.bnAdd.place(relx=0.738, rely=0.136, height=26, width=95)
        self.bnAdd.configure(activebackground="#d9d9d9")
        self.bnAdd.configure(activeforeground="black")
        self.bnAdd.configure(background="#bfbfff")
        self.bnAdd.configure(disabledforeground="#68665a")
        self.bnAdd.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnAdd.configure(foreground="black")
        self.bnAdd.configure(highlightbackground="cornsilk4")
        self.bnAdd.configure(highlightcolor="black")
        self.bnAdd.configure(text='''ADD''', command=self.ADD)

        self.bnUpdate = tk.Button(self.Frame1)
        self.bnUpdate.place(relx=0.738, rely=0.317, height=26, width=97)
        self.bnUpdate.configure(activebackground="#d9d9d9")
        self.bnUpdate.configure(activeforeground="black")
        self.bnUpdate.configure(background="#bfbfff")
        self.bnUpdate.configure(disabledforeground="#68665a")
        self.bnUpdate.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnUpdate.configure(foreground="black")
        self.bnUpdate.configure(highlightbackground="cornsilk4")
        self.bnUpdate.configure(highlightcolor="black")
        self.bnUpdate.configure(text='''UPDATE''', command=self.Update)

        self.Label7 = tk.Label(self.Frame1)
        self.Label7.place(relx=0.039, rely=0.814, height=21, width=74)
        self.Label7.configure(activebackground="#d9d9d9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(anchor='w')
        self.Label7.configure(background="#7171ff")
        self.Label7.configure(compound='left')
        self.Label7.configure(disabledforeground="#68665a")
        self.Label7.configure(font="-family {Arial Black} -size 13 -weight bold")
        self.Label7.configure(foreground="black")
        self.Label7.configure(highlightbackground="cornsilk4")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''D_O_B:''')

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.039, rely=0.679, height=24, width=84)
        self.Label5.configure(activebackground="#d9d9d9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#7171ff")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#68665a")
        self.Label5.configure(font="-family {Arial Black} -size 13 -weight bold")
        self.Label5.configure(foreground="black")
        self.Label5.configure(highlightbackground="cornsilk4")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Gender:''')

        self.Text7 = tk.Text(self.Frame1)
        self.Text7.place(relx=0.214, rely=0.814, relheight=0.109, relwidth=0.299)

        self.Text7.configure(background="white")
        self.Text7.configure(font="TkTextFont")
        self.Text7.configure(foreground="black")
        self.Text7.configure(highlightbackground="#d9d9d9")
        self.Text7.configure(highlightcolor="black")
        self.Text7.configure(insertbackground="black")
        self.Text7.configure(selectbackground="#d9d9d9")
        self.Text7.configure(selectforeground="black")
        self.Text7.configure(wrap="word")

        self.Text6 = tk.Text(self.Frame1)
        self.Text6.place(relx=0.707, rely=0.475, relheight=0.122, relwidth=0.241)

        self.Text6.configure(background="#ffffff")
        self.Text6.configure(font="TkTextFont")
        self.Text6.configure(foreground="black")
        self.Text6.configure(highlightbackground="cornsilk4")
        self.Text6.configure(highlightcolor="black")
        self.Text6.configure(insertbackground="black")
        self.Text6.configure(selectbackground="#d9d9d9")
        self.Text6.configure(selectforeground="black")
        self.Text6.configure(wrap="word")

        self.Text5 = tk.Text(self.Frame1)
        self.Text5.place(relx=0.214, rely=0.679, relheight=0.122, relwidth=0.299)

        self.Text5.configure(background="#ffffff")
        self.Text5.configure(font="TkTextFont")
        self.Text5.configure(foreground="black")
        self.Text5.configure(highlightbackground="cornsilk4")
        self.Text5.configure(highlightcolor="black")
        self.Text5.configure(insertbackground="black")
        self.Text5.configure(selectbackground="#d9d9d9")
        self.Text5.configure(selectforeground="black")
        self.Text5.configure(wrap="word")

        self.Text4 = tk.Text(self.Frame1)
        self.Text4.place(relx=0.214, rely=0.543, relheight=0.122, relwidth=0.299)

        self.Text4.configure(background="#ffffff")
        self.Text4.configure(font="TkTextFont")
        self.Text4.configure(foreground="black")
        self.Text4.configure(highlightbackground="cornsilk4")
        self.Text4.configure(highlightcolor="black")
        self.Text4.configure(insertbackground="black")
        self.Text4.configure(selectbackground="#d9d9d9")
        self.Text4.configure(selectforeground="black")
        self.Text4.configure(wrap="word")

        self.Text3 = tk.Text(self.Frame1)
        self.Text3.place(relx=0.214, rely=0.407, relheight=0.122, relwidth=0.299)

        self.Text3.configure(background="#ffffff")
        self.Text3.configure(font="TkTextFont")
        self.Text3.configure(foreground="black")
        self.Text3.configure(highlightbackground="cornsilk4")
        self.Text3.configure(highlightcolor="black")
        self.Text3.configure(insertbackground="black")
        self.Text3.configure(selectbackground="#d9d9d9")
        self.Text3.configure(selectforeground="black")
        self.Text3.configure(wrap="word")

        self.Text2 = tk.Text(self.Frame1)
        self.Text2.place(relx=0.214, rely=0.271, relheight=0.122, relwidth=0.299)

        self.Text2.configure(background="#ffffff")
        self.Text2.configure(font="TkTextFont")
        self.Text2.configure(foreground="black")
        self.Text2.configure(highlightbackground="cornsilk4")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="#d9d9d9")
        self.Text2.configure(selectforeground="black")
        self.Text2.configure(wrap="word")

        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.214, rely=0.136, relheight=0.122, relwidth=0.299)

        self.Text1.configure(background="#ffffff")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="cornsilk4")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#d9d9d9")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.039, rely=0.543, height=24, width=84)
        self.Label4.configure(activebackground="#d9d9d9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#7171ff")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#68665a")
        self.Label4.configure(font="-family {Arial Black} -size 13 -weight bold")
        self.Label4.configure(foreground="black")
        self.Label4.configure(highlightbackground="cornsilk4")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Grade:''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.039, rely=0.407, height=24, width=84)
        self.Label3.configure(activebackground="#d9d9d9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#7171ff")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#68665a")
        self.Label3.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label3.configure(foreground="black")
        self.Label3.configure(highlightbackground="cornsilk4")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Class:''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.039, rely=0.271, height=24, width=84)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#7171ff")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#68665a")
        self.Label2.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label2.configure(foreground="black")
        self.Label2.configure(highlightbackground="cornsilk4")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Name:''')

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.039, rely=0.136, height=34, width=84)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#7171ff")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#68665a")
        self.Label1.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label1.configure(foreground="black")
        self.Label1.configure(highlightbackground="cornsilk4")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''STUD_ID:''')

    def TeacherPage(self):

        for i in self.top.winfo_children():
            i.destroy()

        self.list1 = tk.Listbox(self.top)
        self.list1.place(relx=0.067, rely=0.549, relheight=0.363, relwidth=0.86)
        self.list1.configure(background="#ffffff")
        self.list1.configure(disabledforeground="#68665a")
        self.list1.configure(font="TkFixedFont")
        self.list1.configure(foreground="black")
        self.list1.configure(highlightbackground="cornsilk4")
        self.list1.configure(highlightcolor="black")
        self.list1.configure(selectbackground="#d9d9d9")
        self.list1.configure(selectforeground="black")

        self.bnback = tk.Button(self.top)
        self.bnback.place(relx=0.067, rely=0.922, height=36, width=77)
        self.bnback.configure(activebackground="#d9d9d9")
        self.bnback.configure(activeforeground="black")
        self.bnback.configure(background="#bfbfff")
        self.bnback.configure(disabledforeground="#68665a")
        self.bnback.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnback.configure(foreground="black")
        self.bnback.configure(highlightbackground="cornsilk4")
        self.bnback.configure(highlightcolor="black")
        self.bnback.configure(text='''Back''', command=self.Homepage)

        self.Label6 = tk.Label(self.top)
        self.Label6.place(relx=0.35, rely=0.0, height=41, width=184)
        self.Label6.configure(activebackground="#d9d9d9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#8588fc")
        self.Label6.configure(compound='left')
        self.Label6.configure(disabledforeground="#68665a")
        self.Label6.configure(font="-family {Arial Black} -size 22 -weight bold")
        self.Label6.configure(foreground="black")
        self.Label6.configure(highlightbackground="cornsilk4")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''TEACHERS''')

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.067, rely=0.098, relheight=0.433
                          , relwidth=0.858)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#7171ff")
        self.Frame1.configure(highlightbackground="cornsilk4")
        self.Frame1.configure(highlightcolor="black")

        self.bnDelete = tk.Button(self.Frame1)
        self.bnDelete.place(relx=0.738, rely=0.633, height=26, width=97)
        self.bnDelete.configure(activebackground="#d9d9d9")
        self.bnDelete.configure(activeforeground="black")
        self.bnDelete.configure(background="#bfbfff")
        self.bnDelete.configure(disabledforeground="#68665a")
        self.bnDelete.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnDelete.configure(foreground="black")
        self.bnDelete.configure(highlightbackground="cornsilk4")
        self.bnDelete.configure(highlightcolor="black")
        self.bnDelete.configure(text='''DELETE''', command=self.Deletet)

        self.bnShow = tk.Button(self.Frame1)
        self.bnShow.place(relx=0.738, rely=0.814, height=26, width=97)
        self.bnShow.configure(activebackground="#d9d9d9")
        self.bnShow.configure(activeforeground="black")
        self.bnShow.configure(background="#bfbfff")
        self.bnShow.configure(disabledforeground="#68665a")
        self.bnShow.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnShow.configure(foreground="black")
        self.bnShow.configure(highlightbackground="cornsilk4")
        self.bnShow.configure(highlightcolor="black")
        self.bnShow.configure(text='''SHOW''', command=self.showdetailst)

        self.bnAdd = tk.Button(self.Frame1)
        self.bnAdd.place(relx=0.738, rely=0.136, height=26, width=95)
        self.bnAdd.configure(activebackground="#d9d9d9")
        self.bnAdd.configure(activeforeground="black")
        self.bnAdd.configure(background="#bfbfff")
        self.bnAdd.configure(disabledforeground="#68665a")
        self.bnAdd.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnAdd.configure(foreground="black")
        self.bnAdd.configure(highlightbackground="cornsilk4")
        self.bnAdd.configure(highlightcolor="black")
        self.bnAdd.configure(text='''ADD''', command=self.ADDt)

        self.bnUpdate = tk.Button(self.Frame1)
        self.bnUpdate.place(relx=0.738, rely=0.317, height=26, width=97)
        self.bnUpdate.configure(activebackground="#d9d9d9")
        self.bnUpdate.configure(activeforeground="black")
        self.bnUpdate.configure(background="#bfbfff")
        self.bnUpdate.configure(disabledforeground="#68665a")
        self.bnUpdate.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnUpdate.configure(foreground="black")
        self.bnUpdate.configure(highlightbackground="cornsilk4")
        self.bnUpdate.configure(highlightcolor="black")
        self.bnUpdate.configure(text='''UPDATE''', command=self.Updatet)

        self.Label7 = tk.Label(self.Frame1)
        self.Label7.place(relx=0.039, rely=0.814, height=21, width=74)
        self.Label7.configure(activebackground="#d9d9d9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(anchor='w')
        self.Label7.configure(background="#7171ff")
        self.Label7.configure(compound='left')
        self.Label7.configure(disabledforeground="#68665a")
        self.Label7.configure(font="-family {Arial Black} -size 13 -weight bold")
        self.Label7.configure(foreground="black")
        self.Label7.configure(highlightbackground="cornsilk4")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''D_O_B:''')

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.039, rely=0.679, height=24, width=84)
        self.Label5.configure(activebackground="#d9d9d9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#7171ff")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#68665a")
        self.Label5.configure(font="-family {Arial Black} -size 13 -weight bold")
        self.Label5.configure(foreground="black")
        self.Label5.configure(highlightbackground="cornsilk4")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Gender:''')

        self.Text7 = tk.Text(self.Frame1)
        self.Text7.place(relx=0.214, rely=0.814, relheight=0.109, relwidth=0.299)

        self.Text7.configure(background="white")
        self.Text7.configure(font="TkTextFont")
        self.Text7.configure(foreground="black")
        self.Text7.configure(highlightbackground="cornsilk4")
        self.Text7.configure(highlightcolor="black")
        self.Text7.configure(insertbackground="black")
        self.Text7.configure(selectbackground="#d9d9d9")
        self.Text7.configure(selectforeground="black")
        self.Text7.configure(wrap="word")

        self.Text6 = tk.Text(self.Frame1)
        self.Text6.place(relx=0.707, rely=0.475, relheight=0.122, relwidth=0.241)

        self.Text6.configure(background="#ffffff")
        self.Text6.configure(font="TkTextFont")
        self.Text6.configure(foreground="black")
        self.Text6.configure(highlightbackground="cornsilk4")
        self.Text6.configure(highlightcolor="black")
        self.Text6.configure(insertbackground="black")
        self.Text6.configure(selectbackground="#d9d9d9")
        self.Text6.configure(selectforeground="black")
        self.Text6.configure(wrap="word")

        self.Text5 = tk.Text(self.Frame1)
        self.Text5.place(relx=0.214, rely=0.679, relheight=0.122, relwidth=0.299)

        self.Text5.configure(background="#ffffff")
        self.Text5.configure(font="TkTextFont")
        self.Text5.configure(foreground="black")
        self.Text5.configure(highlightbackground="cornsilk4")
        self.Text5.configure(highlightcolor="black")
        self.Text5.configure(insertbackground="black")
        self.Text5.configure(selectbackground="#d9d9d9")
        self.Text5.configure(selectforeground="black")
        self.Text5.configure(wrap="word")

        self.Text4 = tk.Text(self.Frame1)
        self.Text4.place(relx=0.214, rely=0.543, relheight=0.122, relwidth=0.299)

        self.Text4.configure(background="#ffffff")
        self.Text4.configure(font="TkTextFont")
        self.Text4.configure(foreground="black")
        self.Text4.configure(highlightbackground="cornsilk4")
        self.Text4.configure(highlightcolor="black")
        self.Text4.configure(insertbackground="black")
        self.Text4.configure(selectbackground="#d9d9d9")
        self.Text4.configure(selectforeground="black")
        self.Text4.configure(wrap="word")

        self.Text3 = tk.Text(self.Frame1)
        self.Text3.place(relx=0.214, rely=0.407, relheight=0.122, relwidth=0.299)

        self.Text3.configure(background="#ffffff")
        self.Text3.configure(font="TkTextFont")
        self.Text3.configure(foreground="black")
        self.Text3.configure(highlightbackground="cornsilk4")
        self.Text3.configure(highlightcolor="black")
        self.Text3.configure(insertbackground="black")
        self.Text3.configure(selectbackground="#d9d9d9")
        self.Text3.configure(selectforeground="black")
        self.Text3.configure(wrap="word")

        self.Text2 = tk.Text(self.Frame1)
        self.Text2.place(relx=0.214, rely=0.271, relheight=0.122, relwidth=0.299)

        self.Text2.configure(background="#ffffff")
        self.Text2.configure(font="TkTextFont")
        self.Text2.configure(foreground="black")
        self.Text2.configure(highlightbackground="cornsilk4")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="#d9d9d9")
        self.Text2.configure(selectforeground="black")
        self.Text2.configure(wrap="word")

        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.214, rely=0.136, relheight=0.122, relwidth=0.299)

        self.Text1.configure(background="#ffffff")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="cornsilk4")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#d9d9d9")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.039, rely=0.271, height=24, width=84)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#7171ff")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#68665a")
        self.Label2.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label2.configure(foreground="black")
        self.Label2.configure(highlightbackground="cornsilk4")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Name:''')

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.039, rely=0.136, height=34, width=84)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#7171ff")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#68665a")
        self.Label1.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label1.configure(foreground="black")
        self.Label1.configure(highlightbackground="cornsilk4")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''TEAC_ID:''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.039, rely=0.407, height=24, width=84)
        self.Label3.configure(activebackground="#d9d9d9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#7171ff")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#68665a")
        self.Label3.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label3.configure(foreground="black")
        self.Label3.configure(highlightbackground="cornsilk4")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Classes:''')

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.039, rely=0.543, height=24, width=84)
        self.Label4.configure(activebackground="#d9d9d9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#7171ff")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#68665a")
        self.Label4.configure(font="-family {Arial Black} -size 13 -weight bold")
        self.Label4.configure(foreground="black")
        self.Label4.configure(highlightbackground="cornsilk4")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Subject:''')

    def AccountPage(self):

        for i in self.top.winfo_children():
            i.destroy()

        self.bnback = tk.Button(self.top)
        self.bnback.place(relx=0.067, rely=0.922, height=36, width=77)
        self.bnback.configure(activebackground="#d9d9d9")
        self.bnback.configure(activeforeground="black")
        self.bnback.configure(background="#bfbfff")
        self.bnback.configure(disabledforeground="#68665a")
        self.bnback.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnback.configure(foreground="black")
        self.bnback.configure(highlightbackground="cornsilk4")
        self.bnback.configure(highlightcolor="black")
        self.bnback.configure(text='''Back''', command=self.Homepage)

        self.Label6 = tk.Label(self.top)
        self.Label6.place(relx=0.35, rely=0.0, height=41, width=194)
        self.Label6.configure(activebackground="#d9d9d9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#8588fc")
        self.Label6.configure(compound='left')
        self.Label6.configure(disabledforeground="#68665a")
        self.Label6.configure(font="-family {Arial Black} -size 22 -weight bold")
        self.Label6.configure(foreground="black")
        self.Label6.configure(highlightbackground="cornsilk4")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''ACCOUNTS''')

        self.list1 = tk.Listbox(self.top)
        self.list1.place(relx=0.067, rely=0.549, relheight=0.363, relwidth=0.877)

        self.list1.configure(background="#ffffff")
        self.list1.configure(disabledforeground="#68665a")
        self.list1.configure(font="TkFixedFont")
        self.list1.configure(foreground="black")
        self.list1.configure(highlightbackground="cornsilk4")
        self.list1.configure(highlightcolor="black")
        self.list1.configure(selectbackground="#d9d9d9")
        self.list1.configure(selectforeground="black")

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.067, rely=0.098, relheight=0.433
                          , relwidth=0.875)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#7171ff")
        self.Frame1.configure(highlightbackground="cornsilk4")
        self.Frame1.configure(highlightcolor="black")

        self.bnShow = tk.Button(self.Frame1)
        self.bnShow.place(relx=0.737, rely=0.814, height=26, width=97)
        self.bnShow.configure(activebackground="#d9d9d9")
        self.bnShow.configure(activeforeground="black")
        self.bnShow.configure(background="#bfbfff")
        self.bnShow.configure(disabledforeground="#68665a")
        self.bnShow.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnShow.configure(foreground="black")
        self.bnShow.configure(highlightbackground="cornsilk4")
        self.bnShow.configure(highlightcolor="black")
        self.bnShow.configure(text='''SHOW''', command=self.showdetailsa)

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.038, rely=0.271, height=24, width=107)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#7171ff")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#68665a")
        self.Label2.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label2.configure(foreground="black")
        self.Label2.configure(highlightbackground="cornsilk4")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''UserName:''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.038, rely=0.407, height=24, width=107)
        self.Label3.configure(activebackground="#d9d9d9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#7171ff")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#68665a")
        self.Label3.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label3.configure(foreground="black")
        self.Label3.configure(highlightbackground="cornsilk4")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Password:''')

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.038, rely=0.543, height=24, width=86)
        self.Label4.configure(activebackground="#d9d9d9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#7171ff")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#68665a")
        self.Label4.configure(font="-family {Arial Black} -size 13 -weight bold")
        self.Label4.configure(foreground="black")
        self.Label4.configure(highlightbackground="cornsilk4")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Salary:''')

        self.Text4 = tk.Text(self.Frame1)
        self.Text4.place(relx=0.272, rely=0.543, relheight=0.122, relwidth=0.299)

        self.Text4.configure(background="#ffffff")
        self.Text4.configure(font="TkTextFont")
        self.Text4.configure(foreground="black")
        self.Text4.configure(highlightbackground="cornsilk4")
        self.Text4.configure(highlightcolor="black")
        self.Text4.configure(insertbackground="black")
        self.Text4.configure(selectbackground="#d9d9d9")
        self.Text4.configure(selectforeground="black")
        self.Text4.configure(wrap="word")

        self.Text3 = tk.Text(self.Frame1)
        self.Text3.place(relx=0.272, rely=0.407, relheight=0.122, relwidth=0.299)

        self.Text3.configure(background="#ffffff")
        self.Text3.configure(font="TkTextFont")
        self.Text3.configure(foreground="black")
        self.Text3.configure(highlightbackground="cornsilk4")
        self.Text3.configure(highlightcolor="black")
        self.Text3.configure(insertbackground="black")
        self.Text3.configure(selectbackground="#d9d9d9")
        self.Text3.configure(selectforeground="black")
        self.Text3.configure(wrap="word")

        self.Text2 = tk.Text(self.Frame1)
        self.Text2.place(relx=0.272, rely=0.271, relheight=0.122, relwidth=0.299)

        self.Text2.configure(background="#ffffff")
        self.Text2.configure(font="TkTextFont")
        self.Text2.configure(foreground="black")
        self.Text2.configure(highlightbackground="cornsilk4")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="#d9d9d9")
        self.Text2.configure(selectforeground="black")
        self.Text2.configure(wrap="word")

        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.272, rely=0.136, relheight=0.122, relwidth=0.299)

        self.Text1.configure(background="#ffffff")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="cornsilk4")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#d9d9d9")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")

        self.Label7 = tk.Label(self.Frame1)
        self.Label7.place(relx=0.038, rely=0.814, height=21, width=97)
        self.Label7.configure(activebackground="#d9d9d9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(anchor='w')
        self.Label7.configure(background="#7171ff")
        self.Label7.configure(compound='left')
        self.Label7.configure(disabledforeground="#68665a")
        self.Label7.configure(font="-family {Arial Black} -size 13 -weight bold")
        self.Label7.configure(foreground="black")
        self.Label7.configure(highlightbackground="cornsilk4")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Staff_ID:''')

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.038, rely=0.679, height=24, width=117)
        self.Label5.configure(activebackground="#d9d9d9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#7171ff")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#68665a")
        self.Label5.configure(font="-family {Arial Black} -size 13 -weight bold")
        self.Label5.configure(foreground="black")
        self.Label5.configure(highlightbackground="cornsilk4")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Teacher_ID:''')

        self.Text7 = tk.Text(self.Frame1)
        self.Text7.place(relx=0.272, rely=0.814, relheight=0.109, relwidth=0.299)

        self.Text7.configure(background="white")
        self.Text7.configure(font="TkTextFont")
        self.Text7.configure(foreground="black")
        self.Text7.configure(highlightbackground="cornsilk4")
        self.Text7.configure(highlightcolor="black")
        self.Text7.configure(insertbackground="black")
        self.Text7.configure(selectbackground="#d9d9d9")
        self.Text7.configure(selectforeground="black")
        self.Text7.configure(wrap="word")

        self.Text5 = tk.Text(self.Frame1)
        self.Text5.place(relx=0.272, rely=0.679, relheight=0.122, relwidth=0.299)

        self.Text5.configure(background="#ffffff")
        self.Text5.configure(font="TkTextFont")
        self.Text5.configure(foreground="black")
        self.Text5.configure(highlightbackground="cornsilk4")
        self.Text5.configure(highlightcolor="black")
        self.Text5.configure(insertbackground="black")
        self.Text5.configure(selectbackground="#d9d9d9")
        self.Text5.configure(selectforeground="black")
        self.Text5.configure(wrap="word")

        self.bnDelete = tk.Button(self.Frame1)
        self.bnDelete.place(relx=0.737, rely=0.679, height=26, width=97)
        self.bnDelete.configure(activebackground="#d9d9d9")
        self.bnDelete.configure(activeforeground="black")
        self.bnDelete.configure(background="#bfbfff")
        self.bnDelete.configure(disabledforeground="#68665a")
        self.bnDelete.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnDelete.configure(foreground="black")
        self.bnDelete.configure(highlightbackground="cornsilk4")
        self.bnDelete.configure(highlightcolor="black")
        self.bnDelete.configure(text='''DELETE''', command=self.Deletea)

        self.Text6 = tk.Text(self.Frame1)
        self.Text6.place(relx=0.718, rely=0.543, relheight=0.122, relwidth=0.24)
        self.Text6.configure(background="#ffffff")
        self.Text6.configure(font="TkTextFont")
        self.Text6.configure(foreground="black")
        self.Text6.configure(highlightbackground="cornsilk4")
        self.Text6.configure(highlightcolor="black")
        self.Text6.configure(insertbackground="black")
        self.Text6.configure(selectbackground="#d9d9d9")
        self.Text6.configure(selectforeground="black")
        self.Text6.configure(wrap="word")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.038, rely=0.136, height=34, width=117)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#7171ff")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#68665a")
        self.Label1.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label1.configure(foreground="black")
        self.Label1.configure(highlightbackground="cornsilk4")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Account_ID:''')

        self.Frame2_1 = tk.Frame(self.Frame1)
        self.Frame2_1.place(relx=0.815, rely=0.045, relheight=0.475
                            , relwidth=0.166)
        self.Frame2_1.configure(relief='groove')
        self.Frame2_1.configure(borderwidth="2")
        self.Frame2_1.configure(relief="groove")
        self.Frame2_1.configure(background="#8588fc")
        self.Frame2_1.configure(highlightbackground="cornsilk4")
        self.Frame2_1.configure(highlightcolor="black")

        self.Label9 = tk.Label(self.Frame2_1)
        self.Label9.place(relx=0.115, rely=0.095, height=13, width=64)
        self.Label9.configure(activebackground="#d9d9d9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(anchor='w')
        self.Label9.configure(background="#8588fc")
        self.Label9.configure(compound='left')
        self.Label9.configure(disabledforeground="#68665a")
        self.Label9.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.Label9.configure(foreground="black")
        self.Label9.configure(highlightbackground="cornsilk4")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''STAFF''')

        self.bnAdds = tk.Button(self.Frame2_1)
        self.bnAdds.place(relx=0.115, rely=0.314, height=26, width=65)
        self.bnAdds.configure(activebackground="#d9d9d9")
        self.bnAdds.configure(activeforeground="black")
        self.bnAdds.configure(background="#bfbfff")
        self.bnAdds.configure(disabledforeground="#68665a")
        self.bnAdds.configure(font="-family {Arial Black} -size 10 -weight bold")
        self.bnAdds.configure(foreground="black")
        self.bnAdds.configure(highlightbackground="cornsilk4")
        self.bnAdds.configure(highlightcolor="black")
        self.bnAdds.configure(text='''ADD''', command=self.ADDas)

        self.bnUpdates = tk.Button(self.Frame2_1)
        self.bnUpdates.place(relx=0.115, rely=0.629, height=26, width=67)
        self.bnUpdates.configure(activebackground="#d9d9d9")
        self.bnUpdates.configure(activeforeground="black")
        self.bnUpdates.configure(background="#bfbfff")
        self.bnUpdates.configure(disabledforeground="#68665a")
        self.bnUpdates.configure(font="-family {Arial Black} -size 10 -weight bold")
        self.bnUpdates.configure(foreground="black")
        self.bnUpdates.configure(highlightbackground="cornsilk4")
        self.bnUpdates.configure(highlightcolor="black")
        self.bnUpdates.configure(text='''UPDATE''', command=self.Updateas)

        self.Frame2_1_1 = tk.Frame(self.Frame1)
        self.Frame2_1_1.place(relx=0.648, rely=0.045, relheight=0.475
                              , relwidth=0.166)
        self.Frame2_1_1.configure(relief='groove')
        self.Frame2_1_1.configure(borderwidth="2")
        self.Frame2_1_1.configure(relief="groove")
        self.Frame2_1_1.configure(background="#8588fc")
        self.Frame2_1_1.configure(highlightbackground="cornsilk4")
        self.Frame2_1_1.configure(highlightcolor="black")

        self.Label9_1 = tk.Label(self.Frame2_1_1)
        self.Label9_1.place(relx=0.0, rely=0.095, height=13, width=84)
        self.Label9_1.configure(activebackground="#d9d9d9")
        self.Label9_1.configure(activeforeground="black")
        self.Label9_1.configure(anchor='w')
        self.Label9_1.configure(background="#8588fc")
        self.Label9_1.configure(compound='left')
        self.Label9_1.configure(disabledforeground="#68665a")
        self.Label9_1.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.Label9_1.configure(foreground="black")
        self.Label9_1.configure(highlightbackground="cornsilk4")
        self.Label9_1.configure(highlightcolor="black")
        self.Label9_1.configure(text='''TEACHER''')

        self.bnUpdatet = tk.Button(self.Frame2_1_1)
        self.bnUpdatet.place(relx=0.115, rely=0.629, height=26, width=67)
        self.bnUpdatet.configure(activebackground="#d9d9d9")
        self.bnUpdatet.configure(activeforeground="black")
        self.bnUpdatet.configure(background="#bfbfff")
        self.bnUpdatet.configure(disabledforeground="#68665a")
        self.bnUpdatet.configure(font="-family {Arial Black} -size 10 -weight bold")
        self.bnUpdatet.configure(foreground="black")
        self.bnUpdatet.configure(highlightbackground="cornsilk4")
        self.bnUpdatet.configure(highlightcolor="black")
        self.bnUpdatet.configure(text='''UPDATE''', command=self.Updateat)

        self.bnAddt = tk.Button(self.Frame2_1_1)
        self.bnAddt.place(relx=0.115, rely=0.314, height=26, width=65)
        self.bnAddt.configure(activebackground="#d9d9d9")
        self.bnAddt.configure(activeforeground="black")
        self.bnAddt.configure(background="#bfbfff")
        self.bnAddt.configure(disabledforeground="#68665a")
        self.bnAddt.configure(font="-family {Arial Black} -size 10 -weight bold")
        self.bnAddt.configure(foreground="black")
        self.bnAddt.configure(highlightbackground="cornsilk4")
        self.bnAddt.configure(highlightcolor="black")
        self.bnAddt.configure(text='''ADD''', command=self.ADDat)

    def LibraryPage(self):

        for i in self.top.winfo_children():
            i.destroy()

        self.list1 = tk.Listbox(self.top)
        self.list1.place(relx=0.067, rely=0.549, relheight=0.363, relwidth=0.86)
        self.list1.configure(background="#ffffff")
        self.list1.configure(disabledforeground="#68665a")
        self.list1.configure(font="TkFixedFont")
        self.list1.configure(foreground="black")
        self.list1.configure(highlightbackground="cornsilk4")
        self.list1.configure(highlightcolor="black")
        self.list1.configure(selectbackground="#d9d9d9")
        self.list1.configure(selectforeground="black")

        self.bnback = tk.Button(self.top)
        self.bnback.place(relx=0.067, rely=0.922, height=36, width=77)
        self.bnback.configure(activebackground="#d9d9d9")
        self.bnback.configure(activeforeground="black")
        self.bnback.configure(background="#bfbfff")
        self.bnback.configure(disabledforeground="#68665a")
        self.bnback.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnback.configure(foreground="black")
        self.bnback.configure(highlightbackground="cornsilk4")
        self.bnback.configure(highlightcolor="black")
        self.bnback.configure(text='''Back''', command=self.Homepage)

        self.Label6 = tk.Label(self.top)
        self.Label6.place(relx=0.367, rely=0.0, height=41, width=164)
        self.Label6.configure(activebackground="#d9d9d9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#8588fc")
        self.Label6.configure(compound='left')
        self.Label6.configure(disabledforeground="#68665a")
        self.Label6.configure(font="-family {Arial Black} -size 22 -weight bold")
        self.Label6.configure(foreground="black")
        self.Label6.configure(highlightbackground="cornsilk4")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''LIBRARY''')

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.067, rely=0.098, relheight=0.433
                          , relwidth=0.858)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#7171ff")
        self.Frame1.configure(highlightbackground="cornsilk4")
        self.Frame1.configure(highlightcolor="black")

        self.bnDelete = tk.Button(self.Frame1)
        self.bnDelete.place(relx=0.738, rely=0.633, height=26, width=97)
        self.bnDelete.configure(activebackground="#d9d9d9")
        self.bnDelete.configure(activeforeground="black")
        self.bnDelete.configure(background="#bfbfff")
        self.bnDelete.configure(disabledforeground="#68665a")
        self.bnDelete.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnDelete.configure(foreground="black")
        self.bnDelete.configure(highlightbackground="cornsilk4")
        self.bnDelete.configure(highlightcolor="black")
        self.bnDelete.configure(text='''DELETE''', command=self.Deletel)

        self.bnShow = tk.Button(self.Frame1)
        self.bnShow.place(relx=0.738, rely=0.814, height=26, width=97)
        self.bnShow.configure(activebackground="#d9d9d9")
        self.bnShow.configure(activeforeground="black")
        self.bnShow.configure(background="#bfbfff")
        self.bnShow.configure(disabledforeground="#68665a")
        self.bnShow.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnShow.configure(foreground="black")
        self.bnShow.configure(highlightbackground="cornsilk4")
        self.bnShow.configure(highlightcolor="black")
        self.bnShow.configure(text='''SHOW''', command=self.showdetailsl)

        self.bnAdd = tk.Button(self.Frame1)
        self.bnAdd.place(relx=0.738, rely=0.136, height=26, width=95)
        self.bnAdd.configure(activebackground="#d9d9d9")
        self.bnAdd.configure(activeforeground="black")
        self.bnAdd.configure(background="#bfbfff")
        self.bnAdd.configure(disabledforeground="#68665a")
        self.bnAdd.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnAdd.configure(foreground="black")
        self.bnAdd.configure(highlightbackground="cornsilk4")
        self.bnAdd.configure(highlightcolor="black")
        self.bnAdd.configure(text='''ADD''', command=self.ADDl)

        self.bnUpdate = tk.Button(self.Frame1)
        self.bnUpdate.place(relx=0.738, rely=0.317, height=26, width=97)
        self.bnUpdate.configure(activebackground="#d9d9d9")
        self.bnUpdate.configure(activeforeground="black")
        self.bnUpdate.configure(background="#bfbfff")
        self.bnUpdate.configure(disabledforeground="#68665a")
        self.bnUpdate.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnUpdate.configure(foreground="black")
        self.bnUpdate.configure(highlightbackground="cornsilk4")
        self.bnUpdate.configure(highlightcolor="black")
        self.bnUpdate.configure(text='''UPDATE''', command=self.Updatel)

        self.Text6 = tk.Text(self.Frame1)
        self.Text6.place(relx=0.707, rely=0.475, relheight=0.122, relwidth=0.241)

        self.Text6.configure(background="#ffffff")
        self.Text6.configure(font="TkTextFont")
        self.Text6.configure(foreground="black")
        self.Text6.configure(highlightbackground="cornsilk4")
        self.Text6.configure(highlightcolor="black")
        self.Text6.configure(insertbackground="black")
        self.Text6.configure(selectbackground="#d9d9d9")
        self.Text6.configure(selectforeground="black")
        self.Text6.configure(wrap="word")

        self.Text5 = tk.Text(self.Frame1)
        self.Text5.place(relx=0.252, rely=0.769, relheight=0.122, relwidth=0.299)

        self.Text5.configure(background="#ffffff")
        self.Text5.configure(font="TkTextFont")
        self.Text5.configure(foreground="black")
        self.Text5.configure(highlightbackground="cornsilk4")
        self.Text5.configure(highlightcolor="black")
        self.Text5.configure(insertbackground="black")
        self.Text5.configure(selectbackground="#d9d9d9")
        self.Text5.configure(selectforeground="black")
        self.Text5.configure(wrap="word")

        self.Text4 = tk.Text(self.Frame1)
        self.Text4.place(relx=0.252, rely=0.588, relheight=0.122, relwidth=0.299)

        self.Text4.configure(background="#ffffff")
        self.Text4.configure(font="TkTextFont")
        self.Text4.configure(foreground="black")
        self.Text4.configure(highlightbackground="cornsilk4")
        self.Text4.configure(highlightcolor="black")
        self.Text4.configure(insertbackground="black")
        self.Text4.configure(selectbackground="#d9d9d9")
        self.Text4.configure(selectforeground="black")
        self.Text4.configure(wrap="word")

        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.252, rely=0.045, relheight=0.122, relwidth=0.299)

        self.Text1.configure(background="#ffffff")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="cornsilk4")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#d9d9d9")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")

        self.Text2 = tk.Text(self.Frame1)
        self.Text2.place(relx=0.252, rely=0.226, relheight=0.122, relwidth=0.299)

        self.Text2.configure(background="#ffffff")
        self.Text2.configure(font="TkTextFont")
        self.Text2.configure(foreground="black")
        self.Text2.configure(highlightbackground="cornsilk4")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="#d9d9d9")
        self.Text2.configure(selectforeground="black")
        self.Text2.configure(wrap="word")

        self.Text3 = tk.Text(self.Frame1)
        self.Text3.place(relx=0.252, rely=0.407, relheight=0.122, relwidth=0.299)

        self.Text3.configure(background="#ffffff")
        self.Text3.configure(font="TkTextFont")
        self.Text3.configure(foreground="black")
        self.Text3.configure(highlightbackground="cornsilk4")
        self.Text3.configure(highlightcolor="black")
        self.Text3.configure(insertbackground="black")
        self.Text3.configure(selectbackground="#d9d9d9")
        self.Text3.configure(selectforeground="black")
        self.Text3.configure(wrap="word")

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.019, rely=0.769, height=24, width=114)
        self.Label5.configure(activebackground="#d9d9d9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#7171ff")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#68665a")
        self.Label5.configure(font="-family {Arial Black} -size 13 -weight bold")
        self.Label5.configure(foreground="black")
        self.Label5.configure(highlightbackground="cornsilk4")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Generation:''')

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.039, rely=0.543, height=44, width=84)
        self.Label4.configure(activebackground="#d9d9d9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#7171ff")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#68665a")
        self.Label4.configure(font="-family {Arial Black} -size 13 -weight bold")
        self.Label4.configure(foreground="black")
        self.Label4.configure(highlightbackground="cornsilk4")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Price:''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.039, rely=0.407, height=34, width=84)
        self.Label3.configure(activebackground="#d9d9d9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#7171ff")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#68665a")
        self.Label3.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label3.configure(foreground="black")
        self.Label3.configure(highlightbackground="cornsilk4")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Author:''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.039, rely=0.226, height=34, width=84)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#7171ff")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#68665a")
        self.Label2.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label2.configure(foreground="black")
        self.Label2.configure(highlightbackground="cornsilk4")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Title:''')

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.039, rely=0.045, height=34, width=84)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#7171ff")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#68665a")
        self.Label1.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label1.configure(foreground="black")
        self.Label1.configure(highlightbackground="cornsilk4")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Book_id:''')

    def StaffPage(self):

        for i in self.top.winfo_children():
            i.destroy()

        self.bnback = tk.Button(self.top)
        self.bnback.place(relx=0.067, rely=0.922, height=36, width=77)
        self.bnback.configure(activebackground="#d9d9d9")
        self.bnback.configure(activeforeground="black")
        self.bnback.configure(background="#bfbfff")
        self.bnback.configure(disabledforeground="#68665a")
        self.bnback.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnback.configure(foreground="black")
        self.bnback.configure(highlightbackground="cornsilk4")
        self.bnback.configure(highlightcolor="black")
        self.bnback.configure(text='''Back''', command=self.Homepage)

        self.Label6 = tk.Label(self.top)
        self.Label6.place(relx=0.367, rely=0.0, height=41, width=174)
        self.Label6.configure(activebackground="#d9d9d9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(anchor='w')
        self.Label6.configure(background="#8588fc")
        self.Label6.configure(compound='left')
        self.Label6.configure(disabledforeground="#68665a")
        self.Label6.configure(font="-family {Arial Black} -size 22 -weight bold")
        self.Label6.configure(foreground="black")
        self.Label6.configure(highlightbackground="cornsilk4")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''   STAFF''')

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.067, rely=0.098, relheight=0.433
                          , relwidth=0.858)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#7171ff")
        self.Frame1.configure(highlightbackground="cornsilk4")
        self.Frame1.configure(highlightcolor="black")

        self.bnShow = tk.Button(self.Frame1)
        self.bnShow.place(relx=0.738, rely=0.814, height=26, width=97)
        self.bnShow.configure(activebackground="#d9d9d9")
        self.bnShow.configure(activeforeground="black")
        self.bnShow.configure(background="#bfbfff")
        self.bnShow.configure(disabledforeground="#68665a")
        self.bnShow.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnShow.configure(foreground="black")
        self.bnShow.configure(highlightbackground="cornsilk4")
        self.bnShow.configure(highlightcolor="black")
        self.bnShow.configure(text='''SHOW''', command=self.showdetailss)

        self.Text1 = tk.Text(self.Frame1)
        self.Text1.place(relx=0.252, rely=0.045, relheight=0.122, relwidth=0.299)

        self.Text1.configure(background="#ffffff")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="cornsilk4")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#d9d9d9")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.039, rely=0.045, height=34, width=84)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#7171ff")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#68665a")
        self.Label1.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label1.configure(foreground="black")
        self.Label1.configure(highlightbackground="cornsilk4")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Staff_id:''')

        self.Text5 = tk.Text(self.Frame1)
        self.Text5.place(relx=0.252, rely=0.769, relheight=0.122, relwidth=0.299)

        self.Text5.configure(background="#ffffff")
        self.Text5.configure(font="TkTextFont")
        self.Text5.configure(foreground="black")
        self.Text5.configure(highlightbackground="cornsilk4")
        self.Text5.configure(highlightcolor="black")
        self.Text5.configure(insertbackground="black")
        self.Text5.configure(selectbackground="#d9d9d9")
        self.Text5.configure(selectforeground="black")
        self.Text5.configure(wrap="word")

        self.Label5 = tk.Label(self.Frame1)
        self.Label5.place(relx=0.039, rely=0.769, height=24, width=94)
        self.Label5.configure(activebackground="#d9d9d9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(anchor='w')
        self.Label5.configure(background="#7171ff")
        self.Label5.configure(compound='left')
        self.Label5.configure(disabledforeground="#68665a")
        self.Label5.configure(font="-family {Arial Black} -size 13 -weight bold")
        self.Label5.configure(foreground="black")
        self.Label5.configure(highlightbackground="cornsilk4")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''D_O_B:''')

        self.Text4 = tk.Text(self.Frame1)
        self.Text4.place(relx=0.252, rely=0.588, relheight=0.122, relwidth=0.299)

        self.Text4.configure(background="#ffffff")
        self.Text4.configure(font="TkTextFont")
        self.Text4.configure(foreground="black")
        self.Text4.configure(highlightbackground="cornsilk4")
        self.Text4.configure(highlightcolor="black")
        self.Text4.configure(insertbackground="black")
        self.Text4.configure(selectbackground="#d9d9d9")
        self.Text4.configure(selectforeground="black")
        self.Text4.configure(wrap="word")

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.039, rely=0.588, height=24, width=84)
        self.Label4.configure(activebackground="#d9d9d9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(anchor='w')
        self.Label4.configure(background="#7171ff")
        self.Label4.configure(compound='left')
        self.Label4.configure(disabledforeground="#68665a")
        self.Label4.configure(font="-family {Arial Black} -size 13 -weight bold")
        self.Label4.configure(foreground="black")
        self.Label4.configure(highlightbackground="cornsilk4")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Gender:''')

        self.Text3 = tk.Text(self.Frame1)
        self.Text3.place(relx=0.252, rely=0.407, relheight=0.122, relwidth=0.299)

        self.Text3.configure(background="#ffffff")
        self.Text3.configure(font="TkTextFont")
        self.Text3.configure(foreground="black")
        self.Text3.configure(highlightbackground="cornsilk4")
        self.Text3.configure(highlightcolor="black")
        self.Text3.configure(insertbackground="black")
        self.Text3.configure(selectbackground="#d9d9d9")
        self.Text3.configure(selectforeground="black")
        self.Text3.configure(wrap="word")

        self.Text2 = tk.Text(self.Frame1)
        self.Text2.place(relx=0.252, rely=0.226, relheight=0.122, relwidth=0.299)

        self.Text2.configure(background="#ffffff")
        self.Text2.configure(font="TkTextFont")
        self.Text2.configure(foreground="black")
        self.Text2.configure(highlightbackground="cornsilk4")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="#d9d9d9")
        self.Text2.configure(selectforeground="black")
        self.Text2.configure(wrap="word")

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.039, rely=0.362, height=44, width=84)
        self.Label3.configure(activebackground="#d9d9d9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(anchor='w')
        self.Label3.configure(background="#7171ff")
        self.Label3.configure(compound='left')
        self.Label3.configure(disabledforeground="#68665a")
        self.Label3.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label3.configure(foreground="black")
        self.Label3.configure(highlightbackground="cornsilk4")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Position:''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.039, rely=0.181, height=44, width=84)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#7171ff")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#68665a")
        self.Label2.configure(font="-family {Arial Black} -size 12 -weight bold")
        self.Label2.configure(foreground="black")
        self.Label2.configure(highlightbackground="cornsilk4")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Name:''')

        self.bnAdd = tk.Button(self.Frame1)
        self.bnAdd.place(relx=0.738, rely=0.09, height=26, width=95)
        self.bnAdd.configure(activebackground="#d9d9d9")
        self.bnAdd.configure(activeforeground="black")
        self.bnAdd.configure(background="#bfbfff")
        self.bnAdd.configure(disabledforeground="#68665a")
        self.bnAdd.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnAdd.configure(foreground="black")
        self.bnAdd.configure(highlightbackground="cornsilk4")
        self.bnAdd.configure(highlightcolor="black")
        self.bnAdd.configure(text='''ADD''', command=self.ADDs)

        self.bnUpdate = tk.Button(self.Frame1)
        self.bnUpdate.place(relx=0.738, rely=0.271, height=26, width=97)
        self.bnUpdate.configure(activebackground="#d9d9d9")
        self.bnUpdate.configure(activeforeground="black")
        self.bnUpdate.configure(background="#bfbfff")
        self.bnUpdate.configure(disabledforeground="#68665a")
        self.bnUpdate.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnUpdate.configure(foreground="black")
        self.bnUpdate.configure(highlightbackground="cornsilk4")
        self.bnUpdate.configure(highlightcolor="black")
        self.bnUpdate.configure(text='''UPDATE''', command=self.Updates)

        self.Text6 = tk.Text(self.Frame1)
        self.Text6.place(relx=0.718, rely=0.452, relheight=0.122, relwidth=0.241)

        self.Text6.configure(background="#ffffff")
        self.Text6.configure(font="TkTextFont")
        self.Text6.configure(foreground="black")
        self.Text6.configure(highlightbackground="cornsilk4")
        self.Text6.configure(highlightcolor="black")
        self.Text6.configure(insertbackground="black")
        self.Text6.configure(selectbackground="#d9d9d9")
        self.Text6.configure(selectforeground="black")
        self.Text6.configure(wrap="word")

        self.bnDelete = tk.Button(self.Frame1)
        self.bnDelete.place(relx=0.738, rely=0.633, height=26, width=97)
        self.bnDelete.configure(activebackground="#d9d9d9")
        self.bnDelete.configure(activeforeground="black")
        self.bnDelete.configure(background="#bfbfff")
        self.bnDelete.configure(disabledforeground="#68665a")
        self.bnDelete.configure(font="-family {Arial Black} -size 11 -weight bold")
        self.bnDelete.configure(foreground="black")
        self.bnDelete.configure(highlightbackground="cornsilk4")
        self.bnDelete.configure(highlightcolor="black")
        self.bnDelete.configure(text='''DELETE''', command=self.Deletes)

        self.list1 = tk.Listbox(self.top)
        self.list1.place(relx=0.067, rely=0.549, relheight=0.363, relwidth=0.86)
        self.list1.configure(background="#ffffff")
        self.list1.configure(disabledforeground="#68665a")
        self.list1.configure(font="TkFixedFont")
        self.list1.configure(foreground="black")
        self.list1.configure(highlightbackground="cornsilk4")
        self.list1.configure(highlightcolor="black")
        self.list1.configure(selectbackground="#d9d9d9")
        self.list1.configure(selectforeground="black")


if __name__ == '__main__':
    # create a variable using tkinter to make frontend with it and then call the class
    top = tk.Tk()
    Toplevel1(top)
    top.mainloop()


#----------------------------BELOW IS SQL CODE-----------------------------------------------------------------

# create database School;
# USE School;
#
# CREATE TABLE students (
# stud_id int PRIMARY KEY,
# Name VARCHAR(15) NOT  NULL,
# class VARCHAR(15) NOT NULL,
# Grade INT,
# Gender CHAR(5) NOT NULL,
# dob date not null );
#
#
# CREATE TABLE Teachers (
# teac_id int PRIMARY KEY,
# Name VARCHAR(15) NOT  NULL,
# class VARCHAR(15) NOT NULL,
# Subject VARCHAR(25),
# Gender CHAR(5) NOT NULL,
# dob date not null );
#
#
# CREATE TABLE Library (
#   book_id INT PRIMARY KEY,
#   title VARCHAR(25) NOT NULL,
#   author VARCHAR(15) NOT NULL,
#   book_price int,
#   genre VARCHAR(20) NOT NULL);
#
# CREATE TABLE Staff (
#   staff_id int PRIMARY KEY ,
#   name VARCHAR(20) NOT NULL,
#   position varchar(20) ,
#   Gender CHAR(5) NOT NULL,
#   dob date not null
# );
#
# CREATE TABLE Accounts (
#   account_id int PRIMARY KEY ,
#   username VARCHAR(25) NOT NULL UNIQUE,
#   password VARCHAR(25) NOT NULL,
#   salary int not null,
#   teacher_id int UNIQUE,
#   FOREIGN KEY (teacher_id) REFERENCES Teachers(teac_id),
#   staff_id int unique,
#   FOREIGN KEY (staff_id) REFERENCES Staff(staff_id)
# );
